=== Wizhi/Raunstrup/Raunstrup/Raunstrup.Core/Xml/report.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="report"
  targetNamespace="http://raunstrup.com/EAL"
  elementFormDefault="qualified"
  xmlns="http://raunstrup.com/EAL report.xsd"
  xmlns:mstns="http://raunstrup.com/EAL"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="report">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="date" type="xs:date" />
        <xs:element name="hours">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:int">
                <xs:attribute name="type" use="required" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="transport">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:int">
                <xs:attribute name="type" use="required" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <!--<xs:element name="transport" type="xs:int" />-->
        <xs:element name="materials">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="material" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:int">
                      <xs:attribute name="quantity">
                        <xs:simpleType>
                          <xs:restriction base="xs:int">
                            <xs:minExclusive value="0" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="projectId" type="xs:int" use="required" />
      <xs:attribute name="employeeId" type="xs:int" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Wizhi/Raunstrup/Raunstrup/Raunstrup.Core/Xml/report.xml
<?xml version="1.0" encoding="utf-8" ?>
<report 
  xmlns="http://raunstrup.com/EAL"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://raunstrup.com/EAL report.xsd"
  projectId="12"
  employeeId="23"
>
  <date>2015-11-17</date>
  <hours type="1">123</hours>
  <transport>123</transport>
  <materials>
    <material quantity="234">1</material>
    <material quantity="234">3</material>
    <material quantity="234">2</material>
    <material quantity="234">5</material>
    <material quantity="234">7</material>
  </materials>
</report>
